name: Build and Publish to PyPI


on: push


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # 指定Python版本
    - name: Install dependencies
      run:
        python -m pip install requests==2.31.0 twine

    - name: Install setuptools and wheel
      run: |
        python -m pip install --upgrade setuptools wheel build

    - name: Generate version number
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Update setup.py with new version
      run: |
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
    - name: Build package
      run: |
        python -m build --sdist --wheel .

    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        twine upload dist/*